# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Talking Elastic
tagline:          'Talking Elasticsearch'
description:      'A blog that contains Elasticsearch tutorials, training and articles.'
url:              http://elasticsearchtraining.github.io
baseurl:          /

author:
  name:           'Rajan Manickavasagam'
  url:            https://github.com/rajanm

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/elasticsearchtraining
