# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Talking Elastic
tagline:          'Talking Elasticsearch'
description:      'A blog that contains tutorials, training and articles on Elasticsearch.'
url:              /
baseurl:          /

author:
  name:           'Rajan Manickavasagam'
  url:            https://github.com/rajanm

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/elasticsearchtraining
